### ISSUE TITLE
about weight maps of image

### ISSUE THREAD

**Issue by yaoliu0803** [mnawfal29/APWNet#1]
Hello, This is a good work, i'm exciting in it.
In your paper, ablation studies part, In order to intuitively reveal the effect of the proposed adaptive pixel weight approach, you further visualize the intermediate outputs as heat maps to indicate the weight maps (𝑊𝑖𝑟, 𝑊𝑣𝑖) of two image pairs in TNO dataset.
And I want to know that how implement visualize outputs?  Can you supply code about it?

**Comment by doubolin** [comment]
您好，我再复现您代码的过程中出现了这样的报错，您可以给予帮助吗
Traceback (most recent call last):
  File "D:\doucument\image fusion\code\APWNet-main\train.py", line 291, in <module>
    train(hyp, opt, device)
  File "D:\doucument\image fusion\code\APWNet-main\train.py", line 161, in train
    fusion_image = YCrCb2RGB(fusion_ycrcb)
  File "D:\doucument\image fusion\code\APWNet-main\train.py", line 78, in YCrCb2RGB
    3,
RuntimeError: shape '[16, 480, 640, 3]' is invalid for input of size 24576000
如可以回复，万分感谢，邮箱1794428576@qq.com

**Comment by sy-nj** [comment]
请问数据集的lable是什么格式呢？
